# Playbook Information
#  - This playbook sets up Wordpress on an existing Linux Web Server and connects to a Linux MYSQL server

- name: Create wordpress mysql user and table
  hosts: "{{ databaseserver_hostname  }}"
  gather_facts: no
  become: yes
  vars:
    ansible_become_password: '{{ data_ansible_become_password }}'
  vars_files:
    - vars_wordpress.yml
    - ../secrets.yml

  tasks:
    - name: create database
      community.mysql.mysql_db:
        name: wordpress
        login_user: root
        login_password: '{{ mysql_root_password }}'

    - name: create user & assign to new database
      community.mysql.mysql_user:
        name: wordpress_admin
        password: '{{ wordpress_admin_password }}'
        host: '%'
        login_user: root
        login_password: '{{ mysql_root_password }}'
        priv: 'wordpress.*:ALL,GRANT'

    - name: change bind-address
      ansible.builtin.lineinfile:
        path: /etc/mysql/mysql.conf.d/mysqld.cnf
        regexp: '^bind-address.*'
        line: "bind-address = 0.0.0.0"

    - name: restart mysql
      ansible.builtin.service:
        name: mysql
        state: restarted


- name: Setup Wordpress
  hosts: "{{ webserver_hostname  }}"
  gather_facts: no
  become: yes
  vars:
    ansible_become_password: '{{ web_ansible_become_password }}'
  vars_files:
    - vars_wordpress.yml
    - ../secrets.yml

  tasks:
    - name: remove default apache webpage
      ansible.builtin.file:
        path: /var/www/html/index.html
        state: absent

    - name: download wordpress
      ansible.builtin.get_url:
        url: 'https://wordpress.org/latest.tar.gz'
        dest: /tmp/wordpress.tar.gz

    - name: extract wordpress
      ansible.builtin.unarchive:
        src: /tmp/wordpress.tar.gz
        dest: /tmp/
        remote_src: yes

    - name: copy wordpress files to /var/www/html
      ansible.builtin.copy:
        src: /tmp/wordpress/
        dest: /var/www/html
        remote_src: yes

    - name: copy sample config file
      ansible.builtin.copy:
        src: /var/www/html/wp-config-sample.php
        dest: /var/www/html/wp-config.php
        remote_src: yes

    - name: change folder permissions
      ansible.builtin.command: |
        chown www-data:www-data -R /var/www/html
        chmod -R 755 /var/www/html

    - name: edit wp-config with database settings
      ansible.builtin.lineinfile:
        path: /var/www/html/wp-config.php
        regexp: '^define.*{{ item.key }}.*$'
        line: "define( '{{ item.name }}', '{{ item.value }}' );"
      with_items:
        - { key: "database_name_here", name: "DB_NAME", value: "wordpress" }
        - { key: "username_here", name: "DB_USER", value: "wordpress_admin" }
        - { key: "password_here", name: "DB_PASSWORD", value: "{{ wordpress_db_password }}" }
        - { key: "localhost", name: "DB_HOST", value: "{{ databaseserver_ip}}:3306" }

    - name: restart apache
      ansible.builtin.service:
        name: apache2
        state: restarted

    - name: download wordpress command line interface
      ansible.builtin.get_url:
        url: https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar
        dest: /usr/local/bin/wp
        mode: "0755"

    - name: final wordpress website setup
      ansible.builtin.command: wp core install --url="http://{{ webserver_ip }}"  --title="{{ wp_title }}" --admin_user="{{ wp_user }}" --admin_password="{{ wp_password }}" --admin_email="{{ wp_email }}" --path="/var/www/html" --allow-root
